# Discussion

The purpose of this thesis was to explore the healthiness and environmental impact of recipes found on Internet recipe sites or in recipe books, from Norway, the UK and the US, and to see if origin country influenced a recipe's healthiness or environmental impact, in addition to the correlation between a recipe's healthiness and environmental impact. To our knowledge, this is the first study to explore environmental impact of recipes from either the Internet or recipe books, the first study explore at the healthiness of recipes from Norwegian Internet recipe sites, and the first study on healthiness of recipes to use the NNR and Nutriscore and include a wide range of micronutrients.

## Healthiness and environmental impact

In line with previous studies on recipe healthiness that looked at compliance with the macronutrient requirements from dietary guidelines [@Howard2012; @Jones2013; @Schneider2013; @Keogh2019; @Dickinson2018; @Trattner2017a; @Cheng2021], the results from this thesis showed that only a small percentage of recipes were compliant. The macronutrient content of the Norwegian dinner recipes varied slightly from a previous study of the nutrient content of Norwegian dinners, based on data from the Norwegian national diet survey Norkost 3 that was performed in 2010/2011 [@Myhre2016]. Compared to dinners in Norkost 3, the Norwegian recipes in this thesis had a lower E% from carbohydrates and added sugar, a higher E% of total fat, while the E% from saturated fat and protein and the amount of dietary fibre were similar. This could suggest that in the recipes ingredients that contribute to carbohydrate content have been exchanged for ingredients that contribute fat, specifically unsaturated fats as there were little difference in saturated fat content. A possible explanation could be that the recipes from Norway are of a newer date, and follow the trend of a decreased E% from carbohydrate and increased E% from fat that has been seen in Norwegian diets since Norkost 3 was performed [@Helsedirektoratet2021a] (p37). This pattern of decreased intake of carbohydrates and increased intake of fat has also been observed in the US [@Shan2019].

Fewer recipes were compliant with the WHO than the NNR guidelines, that allows for less carbohydrates and more fat. When looking at the front of pack labels, the FSA MTL and the Nutriscore, the majority of recipes were classified as foods that could be consumed most of the time as part of a healthy diet. That the front of pack labels showed that most recipes could be consumed often, while the same recipes were not compliant with the dietary guidelines, is likely due to the different design and purpose of these indicators, that will be discussed in more detail later. There were statistically significant differences between countries on the total score of the healthiness indicators, but these differences were small and are unlikely to have clinical relevance.

The FSA MTL findings from this thesis are different than other studies that have used a traffic light system to classify recipes and found that their nutritional qualities are low [@Dickinson2018; @Irwin2017; @Wademan2020]. This is likely due to a difference in interpretation of the FSA MTL, and the use of other traffic light systems with different threshold values for nutrients and different interpretations of the traffic light colors. Dickinson et al. [@Dickinson2018] found that recipes on clean eating blogs did not comply well with WHO criteria, and that this was reflected in the recipes also having amber-red lights on the FSA MTL. However, in the guide to interpretation of the FSA MTL [@BritishNutritionFoundation2019], it is said that a food that has mostly amber colored lights can be eaten "most of the time", which suggests it is not unhealthy. In line with this, a recipe that had mostly amber lights, which could mean three amber and one red light, were not considered unhealthy in this thesis. Irwin et al. [@Irwin2017] found that few recipes were healthy when using the Australian Healthy Eating Advisory Service traffic light system (HEAS) where an amber light does not mean "can be eaten most of the time" as in the FSA MTL, but rather "consume in moderation" [@HEAStrafficlights]. The same is true for the study by Wademan et al. [@Wademan2020] that used the Australian LiveLighter traffic light system (LL), where amber means the food is "okay sometimes". Additionally the LL also has more stringent nutrients criteria than the FSA MTL, with the amber criteria from FSA MTL overlapping with the red criteria from the LL. If this is true for the HEAS as well is difficult to say as in contrast to the FSA MTL and the LL criteria, the HEAS varies depending on the type of food, including different types of dinner main and side dishes.

Similar to how the proportion of red meat and total amount of meat could explain most the the variance in the environmental impact of European diets [@Merten2019], recipes from the US that had more recipes with red meat and a higher amount of meat based products also had the highest environmental impact. Additionally, there were a higher proportion of recipes from the US that used shellfish as an ingredient, which also has a high environmental impact.

The World Wide Fund for Nature's "One Planet Plate" concept [@WWFSverige2021] and the menu at the 26th UN Climate Change Conference of the Parties in Glasgow 2021 [@COP26menu] used 0.5 kg CO~2~, the same as the median GHGE per 100 grams of all recipes in this thesis, as the upper limit for a sustainable or low CO~2~ emission for a single meal. The GHGE from the SHARP database used in this thesis include acidification in the form of CO~2~ equivalents, and also include the emissions related to preparation and cooking of food at home, which are not included in the One Planet Plate concept calculations. Still, based on the standard portion sizes for protein food and starchy staples by Dalane et al. [@ØsterholtDalane2015], a dinner portion is about 400 g, which would suggest that few recipes in this thesis would have CO~2~ emissions \<0.5 kg. The lower 25% percent of all recipes, and the lower 50% of the UK recipes, would fit into the "moderate" CO~2~ emission category with an upper limit of 1.8 kg CO~2~ (One Planet Plate) and 1.6 kg CO~2~/meal (Climate Change Conference Menu). The majority of all recipes would then be left in the "high" category. However, this approach does not take into account that portion sizes likely vary by recipe (see the "Strengths, limitations and future work" subchapter). 

### Micronutrient content and specific food recommendations

A diet is not sustainable if it cannot provide the nutrients needed to promote an individual's health and wellbeing.

FBDGs from all three countries have specific recommendations for certain food groups. These include recommendations to choose whole grain products instead of refined grains, consume at least "five a day" of fruit and vegetables, and consume seafood throughout the week [@norskekostraad; @USdietaryguidelines2020; @NHSfood]. These foods are recommended as they contribute important nutrients to the diet, and a higher consumption is believed to improve health and well being.

Nearly all dinner recipes were sources of protein, with most also being a source of phosphorus which is commonly found in protein rich foods such as cheese, fish and meat. This is also the case for vitamin B12 [@NorwegianFoodSafetyAuthority2020]. While few recipes were sources of either retinol or beta-carotene, they can both be utilized by the body as vitamin A, and more recipes contained enough of both to be sources of vitamin A. 

Few recipes included whole grain ingredients, and few recipes had high scores for fruit, vegetable, legume and nut content on the Nutriscore. It is therefore not surprising, though still unfortunate, that few recipes were sources of nutrients found in these foods, such as beta-carotene, folate, magnesium, iron and potassium [@NorwegianFoodSafetyAuthority2020]. More recipes from the UK, that tended to include more vegetables than recipes from Norway and the US, were sources of these nutrients. Additionally more recipes from the UK were sources of dietary fibre that is also found in these foods, and vitamin C that is found in vegetables and fruit specifically. This is likely contributing to recipes from the UK performing slightly better on the Nutriscore than recipes from the other two countries.

That few recipes were sources of iodine reflects that few recipes included white lean fish, one of the few dietary sources of this mineral [@NorwegianFoodSafetyAuthority2020]. If the low use of lean fish as an ingredient in this sample is reflective of dinner recipes from these sources overall, it is unfortunate as mild to moderate iodine deficiency could be a problem for vulnerable groups, especially pregnant women, in all the three countries the recipes are sourced from [@Meltzer2016; @Woodside2021; @Panth2019]. 

For the Norwegian recipes, the percentage of recipes with fish is in line with the national FBDG, that advises consumption of at least two-three fish dinners a week, corresponding to 28-43% of a week's dinners. The ratio between lean and oily fish, about 1:1, is also in line with the guidelines [@norskekostraad]. For the UK recipes the percentage of recipes is below the recommended two portions of fish a week [@NHSfood], but also for the UK recipes the ratio between lean and oily fish is in line with guideline recommendations of 1:1. Unlike the Norwegian and UK FBDGs, the US FBDG do not give specific advice for fish intake, but rather group fish and shellfish together into a seafood category and advice an intake of 227 g/week [@USdietaryguidelines2020], corresponding to a bit more than one portion from the UK or Norway. This is in line with the percentage of seafood recipes from the US.

It should be mentioned that for lean fish, there is no upper limit on intake in any of these countries' FBDGs. In contrast, both Norway and the UK advice that intake of red meat should be \<500 g/week, which corresponds to two-three dinners and some meat based cold-cuts according to the Norwegian FBDG [@norskekostraad]. The Norwegian recipes are in line with this, while the UK recipes are slightly above. The US FBDG does not have individual guidelines for red meat intake. Surprisingly, despite red meat being a common ingredient in recipes from all countries, few recipes were considered sources of iron, for which red meat is a commonly mentioned source. While surprising, this is not necessarily concerning as unlike iodine iron can be found in many other staple foods that are eaten throughout the day, such as grains and legumes already mentioned [@NorwegianFoodSafetyAuthority2020]. Additionally, the bioavailability of iron from meat is between 15-35% [@Monsen1988], while the RDI for iron is based on a bioavailability of 15% to account for lower bioavailability from plant based sources [@Helsedirektoratet2014]. In this thesis the RDI for nutrients were based on the needs of women, who have higher iron requirements than men due to menstrual bleeding [@Helsedirektoratet2014]. It is possible more recipes would have been considered sources of iron for men. 

Other nutrients that few dinner were sources of, such as riboflavin and calcium, can like iron be found in several other foods that are likely to be eaten throughout the day. A single meal such as a dinner does not have to be a source of all nutrients, but when planning a weekly menu it is important with variety so that all RDIs are met. 

### Nutrient content and environmental impact

Meeting RDIs should not put undue strain on the environment.

Nutrients found in high amounts in animal sourced foods, like saturated fat, protein, iron, zinc, phosphorus, retinol, vitamin B12 and riboflavin were the nutrients that were positively correlated with environmental impact. Interestingly, this varied a little by country. For zinc and iron, the correlation with GHGE were lower in the UK recipes than recipes from Norway and the US, suggesting that more zinc and iron in the UK recipes came from plant based foods rather than animal sourced foods with a higher environmental impact. While iron were significantly higher in the UK than the Norwegian recipes, this difference was clinically irrelevant. This is the same for the significant difference in zinc content between the Norwegian and the US recipes.

While the UK recipes provided iron and zinc at a lower environmental cost, as already mentioned these minerals have lower bioavailability when they come from plant based sources rather than animal sourced foods and so the amounts can not be directly compared [@Platel2016]. There are however ways to increase the bioavailability of these nutrients from plants, such as soaking, sprouting and combining plants with different nutrients that improve absorption, for example plant-based iron is easier absorbed if consumed together with an acid like vitamin C. For vitamin B12 and protein, the correlation was stronger for GHGE than landuse, likely due to these nutrients being provided not only by meat but also seafood that has a lower land requirement than meat, but could still have the same GHGE, in the SHARP database. This could also explain the different strength of the correlation of the individual countries, as different types of seafood were used in the recipes from each country.

For the nutrients vitamin D and iodine, there was a negative correlation with landuse but not GHGE. This is also likely due to these nutrients mainly being found in seafood.

For nutrients found almost exclusively in plants, such as beta-carotene, vitamin C, carbohydrates and fibre there were a negative correlation with environmental impact. This was also the case for folate, but to a lesser extent. Possibly because folate is not exclusive to plants but can also be found in animal sourced foods, like liver and eggs. For sugar, which is also a plant based food, there was a positive correlation with both GHGE and landuse. This is likely an artifact due to sugar being used in marinades or sauces in meat based recipes.

That important micronutrients were positively correlated with GHGE and landuse, underscore the importance of including micronutrient content when planning low GHGE diets. The association between these nutrients and GHGE is likely the reason why in studies on self-selected diets, low GHGE does not always align with higher nutritional quality [@Anitha2021; @Masset2014]. In a recent modelling study by Perignon et al. [@Perignon2016], moderate GHGE reductions (defined as $\leq$ 30%) were possible without compromising nutrient adequacy. Larger reductions were possible, but would require non-trivial changes in food consumption patterns. As with nutrient content, it is important to look at the whole diet over a period of time when looking at environmental impact. A high environmental impact of one meal could be offset by a lower environmental impact of another meal.

### Differences between the front of pack labeling schemes and the dietary guidelines

Dietary guidelines for macronutrient intake are designed to to be used to assess the nutrient quality of whole diets, not single meals. Macronutrient guidelines alone do not ensure that a diet contains necessary micronutrients, which is why they are combined with advice on specific foods that should be included in a daily/weekly diet. On the other hand, the FSA MTL and the Nutriscore is designed to provide at-a-glance information about a specific product and help consumers make healthier food choices. That particular food by itself does not necessarily comply with all dietary guidelines, but by consistently buying the recommended foods within a varied set of food groups, dietary quality is likely to improve. The Nutriscore have consistently been shown to give A/B scores for foods which are encouraged in FBDGs [@Ahmed2020; @Chantal2015; @SzabodeEdelenyi2019; @Dreano-Trecant2020], although for combination dishes such as ready meals that are comparable to the dinner recipes in this study, the alignment with dietary guidelines have been found to be lower than for other food categories [@Ahmed2020; @VanTongeren2020]. Unlike the other three indicators, the Nutriscore balance unhealthy disqualifying components of a food with healthy qualifying components. This means a food product can receive a healthy label if the score on the qualifying components outweigh the score of disqualifying components. 

While the recipes defined as healthy or a meal that could be eaten often as part of a healthy diet varied between the indicators, the positive correlation between the indicators indicate that they pick up on similar nutrient qualities in the recipes.

The differences between how the scores are calculated also likely explain why the dietary guidelines had a stronger correlation with environmental impact than the front of pack labels. All the healthiness indicators penalize a high content of saturated fats, found almost exclusively in high environmental impact animal sourced foods, but also a few vegetable fats such as coconut and palm oil [@NorwegianFoodSafetyAuthority2020]. All but the FSA MTL reward higher dietary fibre content, found in low environmental foods such as whole grains, fruits and vegetables including starchy roots and tubers, legumes and nuts. The most important difference is likely between how total carbohydrates and protein content is scored. The dietary guidelines reward a moderate to high total carbohydrate content and penalize too high protein content, while Nutriscore does not include total carbohydrates and protein is a qualifying component of the score with no upper limit penalty, and the FSA MTL does not include either.

Effectively this means recipes with a higher score on the dietary guidelines would likely have a higher content of low environmental impact foods such as starchy roots and tubers, grains, legumes and fruit, rich in total carbohydrates, while penalizing those recipes that contained a high amount of high environmental impact meat that is rich in protein. On the other hand, a recipe with a high score on the Nutriscore could still include high amounts of meat, as long as it was a cut low in saturated fat, which would give these recipes a higher environmental impact. For the specific recipes in this study, the median qualifying score from protein alone outweighed or neutralized the total median disqualifying scores on the Nutriscore.

As the FSA MTL does not include either carbohydrates, fibre or protein content, a higher score is not as tied to a high content of low environmental ingredients as the dietary guidelines, but it is neither associated with a higher content of high environmental ingredients which could happen with the protein in the Nutriscore.

Surprisingly, adherence to the NNR guidelines, with its lower carbohydrate and higher fat allowances, was slightly stronger correlated to reduced environmental impact than adherence to the WHO guidelines. This could be because more recipes were awarded points for carbohydrate content with NNR than WHO guidelines.

## Strengths, limitations and future work

The strengths of this thesis were the inclusion of other micronutrients than sodium in the analysis, which is unique in the field of recipe healthiness, and the use of multiple healthiness indicators. The healthiness indicators are used in many different countries, making the results of the healthiness and correlation analyses applicable outside of the countries of origin of the recipes included. All analyses and ingredient-to-database mapping are available as R scripts, and can easily be reproduced.

There are several limitations of the data and methods used in this thesis. It was discovered that some online recipes would include additional ingredients in their description to be served with the recipe, not included in the ingredients list that had been added to the database used to calculate nutrient content and environmental impact. For example "serve with potatoes, rice or salad". These are ingredients that would have altered the healthiness scores and lowered the environmental impact, by providing more carbohydrate and/or fibre rich foods, had they been included in the analyses. This could possibly explain why recipes from the UK, which were from chef's recipe books and possibly were more detailed, performed better on the healthiness indicators. Another issue with the online recipes were that not all recipes were classified correctly by meal type, as both desert, lunch and appetizers were found classified as dinner recipes. 

Some ingredients that contributed to the nutrient calculations, and thus influenced healthiness scores, were not ingredients that would be eaten in full in the final recipe. For example oil in marinades or vegetables is soup bases. This is only relevant for the healthiness, and not environmental impact, as the environmental impact of these ingredients are the same regardless of if they are eaten or not. The final weight of soups, stews and recipes with certain sauces are likely inflated due to the inclusion of high amounts of water, that would have diluted the other ingredients when calculating nutrient content and environmental impact per 100 grams.

Analyzing the nutrient content and environmental impact per 100 grams could limit the real world usefulness of the results, as a typical dinner is likely more than 100 grams. Using portion size could perhaps have been a better choice, but not all recipes provided the number of portions per recipe. This might have been solved by using standardized portion sizes of protein included in the recipe, but this approach does not take into account that portion sizes may vary by recipe, and this in itself could be a source of different nutrient content and environmental impact between different recipe sources. 

The use of the SHARP database, that is based on LCAs from a handful of European countries, means that the results may not be relevant to inhabitants of the countries the recipes in this study comes from. Nutrient content in food composition databases may also not accurately depict the nutrient content of foods available to the consumers, which could influence results of nutrient content analyses and the correlation of the various nutrients with environmental impact. The SHARP database also only include information about GHGE and landuse, and not other indicators of environmental impact such as water use, eutrophication and impact on biodiversity.

Unfortunately, there were no data on the cost or acceptability of these recipes, which are the two remaining domains of the sustainable diet concept.

While the aim of this thesis was to explore nutrient content and environmental impact of dinner recipes, future research should include other types of meals to see how nutrient composition and environmental impact varies depending on meal type. Or look at meals following a specific dietary strategy, such as a national FBDGs, plant based or others. It would also be possible to look at whole meal plans, from recipe sites, blogs or books, to see how sustainable they are.

It would be important to take into account that some ingredients may not be mentioned in the recipe ingredient list, but rather in the text description, and that recipes may be misclassified. Further, macronutrient guidelines should not be used for analysing the healthiness of single meal type recipes, although they could be suitable for meal plans that include a whole day or more of meals. Especially if they include some of the food based advice, such as "five a day" or "eat fish two-three times a week". For single meals it would be useful to find better indicators for health, also to improve the comparability between different studies. The Nutriscore has an advantage in that it includes foods that are encouraged in FBDGs and are likely to contribute important micronutrients: fruits, vegetables, nuts, legumes and healthy fats, but its useability with complex meals such as the dinner recipes in this thesis is uncertain.

Further, cost and acceptability of recipes should also be explored. For example cost could come from online stores, and some online recipe sources provide user ratings that could be used as a stand-in for acceptability. Additionally, it would have been interesting to include more environmental impact indicators. Thresholds should be developed to find categories to describe the sustainability of meals.

## Conclusion

This thesis showed that the type of healthiness indicator used can influence if a recipe is classified as healthy or not, and that there were few differences between recipe healthiness, CO~2~ emission and landuse and country of origin. Recipes scored worse on adherence to WHO and Nordic Nutritional Recommendation dietary guidelines on macronutrient intake than on the front of pack labels the UK's Food Standard Agency Multiple Traffic Light system and the Nutriscore. For all four healthiness indicators there was a negative correlation with environmental impact, with a stronger correlation being found between dietary guidelines and environmental impact than between the front of pack labels and environmental impact. Nutrients predominantly found in animal sourced foods, including protein, vitamin B12, retinol, iron and zinc, were positively correlated with environmental impact, while nutrients found in plant based foods, including carbohydrates, fibre and vitamin C, were negatively correlated with environmental impact. It was also found that few recipes were either vegetarian, vegan, or included whole grains or seafood, even though all countries of origin encourage the intake of plant based foods, whole grains and seafood in their food based dietary guidelines. This also likely contributed to few recipes being sources of the micronutrients beta-carotene, folate, magnesium, potassium, iodine and iron.
